# версия docker-compose
version: '3.3'

# имя директории для хранения данных
volumes:
  postgres_data:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:latest
    # volume и связанная с ним директория в контейнере
    environment:
      POSTGRES_PASSWORD: postgres55
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: gunicorn yatube_api.wsgi:application --bind 0.0.0.0:8000 --timeout 90
    ports:
      - "5000:8000"
    # "зависит от", 
    depends_on:
      - db
    env_file:
      - ./.env